### ISSUE TITLE
Document Stack support

### ISSUE THREAD

**Issue by spinda** [atom-haskell/ide-haskell#166] opened 2016-06-09 03:34 UTC
re: #82

Apparently you support Stack now. Why not tell the world? :wink:

I'd submit a PR but I don't know what setup is involved.

**Comment by lierdakil** [comment] 2016-06-09 07:30
Duplicate of #163.
9 июня 2016 г. 6:34 AM пользователь "Michael Smith" <
notifications@github.com> написал:

**Comment by radix** [comment] 2016-07-29 19:54
I suppose this ticket should be closed, if it's a duplicate?

**Comment by lierdakil** [comment] 2016-07-29 20:08
Yes. I didn't have access to github at the time, and later just forgot.

**Closed** 2016-07-29 20:08 UTC
