### ISSUE TITLE
Literate Haskell support

### ISSUE THREAD

**Issue by awalterschulze** [atom-haskell/ide-haskell#75] opened 2015-06-20 11:57 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.210.0
**System**: Mac OS X 10.10
**Thrown From**: [ide-haskell](https://github.com/atom-haskell/ide-haskell) package, v0.5.13

### Stack Trace

Uncaught TypeError: Cannot read property 'showExpressionType' of undefined

```
At /Users/walter/.atom/packages/ide-haskell/lib/ide-haskell.coffee:221

TypeError: Cannot read property 'showExpressionType' of undefined
  at atom-text-editor.disposables.add.atom.commands.add.ide-haskell:show-type (/Users/walter/.atom/packages/ide-haskell/lib/ide-haskell.coffee:221:55)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:150:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -1:23.3.0 application:add-project-folder (atom-text-editor.editor.is-focused)
     -1:06.2.0 core:save-as (atom-text-editor.editor.is-focused)
     -0:35.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:35.1.0 ide-haskell:close-tooltip (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "base16-tomorrow-light-theme"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "audioBeep": false,
    "projectHome": "/Users/walter/code/xhaskell-library",
    "disabledPackages": [
      "metrics"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.4.4
haskell-ghc-mod, v0.7.8
ide-haskell, v0.5.13
language-haskell, v1.1.4

# Dev
No dev packages
```

**Comment by lierdakil** [comment] 2015-06-20 18:10
Due to health issues,  I cannot dedicate much time  to this. Regardless,
I'd like to ask you to provide some details on reproducing this error. I
cannot say I understand how you got this in the first place. Thank you.
20 июня 2015 г. 14:57 пользователь "Walter Schulze" <
notifications@github.com> написал:

**Comment by awalterschulze** [comment] 2015-06-20 18:41
I was asking Atom to Show Expression Type of Range in this line

https://github.com/awalterschulze/xhaskell-library/blob/master/Text/Regex/PDeriv/ByteString/LeftToRightD.lhs#L41

I hope this helps and I hope you get well soon.

**Comment by lierdakil** [comment] 2015-06-20 19:21
Thanks, I think I get now what happens. I don't think that literal haskell
will work. Sorry about that. I'll try to fix this when I'm able to.

20 июня 2015 г. 21:41 пользователь "Walter Schulze" <
notifications@github.com> написал:
>
> I was asking Atom to Show Expression Type of Range in this line
>
>
https://github.com/awalterschulze/xhaskell-library/blob/master/Text/Regex/PDeriv/ByteString/LeftToRightD.lhs#L41

**Comment by awalterschulze** [comment] 2015-06-20 19:52
Aha ok so it should work for normal haskell, but will only work for literal haskell once this bug is fixed.
Thank you for the feedback :)

**Comment by lierdakil** [comment] 2015-06-26 09:16
Initial support for literate haskell is released with ide-haskell 0.5.14 and haskell-ghc-mod 0.7.10. Bear in mind that linting doesn't work for `lhs` (seems like hlint bug), so it was disabled internally.

**Comment by awalterschulze** [comment] 2015-06-26 11:52
Good to hear.
I basically switched to atom from sublime just because there was highlighting for lhs.
Then atom made it really easy to report a bug.

**Comment by lierdakil** [comment] 2015-06-26 11:55
Truth be told, highlighting for lhs could use some work still. I'll make it a point to look at it soon (-ish)

**Comment by awalterschulze** [comment] 2015-06-26 11:58
I thought the highlighting was at least acceptable.

**Comment by lierdakil** [comment] 2015-06-26 12:48
Okay, language-haskell v1.1.5 should have better syntax highlighting for lhs. Feel free to report any problems with that at https://github.com/atom-haskell/language-haskell/issues

**Comment by lierdakil** [comment] 2015-07-31 10:48
I'll open new issue concerning linting not working with lhs. I feel like the rest is decent enough.

**Closed by lierdakil** 2015-07-31 10:48 UTC
Labels: enhancement, in progress

**Comment by awalterschulze** [comment] 2015-07-31 13:27
Maybe you could add the new issue link here?

**Comment by lierdakil** [comment] 2015-07-31 13:29
Done.
