### ISSUE TITLE
Atom 1.15.0 + ide-haskell 1.9.6 = no type info on mouseover

### ISSUE THREAD

**Issue by ThomasLocke** [atom-haskell/ide-haskell#201] opened 2017-03-13 16:06 UTC
It works with Atom 1.14.3 and ide-haskell 1.9.6, so there seems to be something going on somewhere between 1.14.3 and 1.15.0

The console outputs the following on mouseover:

 ```
haskell-ghc-mod warning: ghc-modi said: EXCEPTION: types: attempting to use module ‘Main’ (src/Main.hs) which is not loaded
util.coffee [sm]:36 haskell-ghc-mod warning: ghc-modi said: EXCEPTION: info:
util.coffee [sm]:36 haskell-ghc-mod warning: ghc-modi said:                attempting to use module ‘Main’ (src/Main.hs) which is not loaded
upi.coffee:157 Error: Got neither type nor info(…)
```

I've also submitted this issue to haskell-ghc-mod, since I'm not sure if the problem is here or there: https://github.com/atom-haskell/haskell-ghc-mod/issues/207

**Comment by lierdakil** [comment] 2017-03-14 00:36
Huh. That's strange. Well, one thing's for sure, I can't reproduce this on my end. The most likely explanation is that Atom changed something in how it handles system environment, and now suddenly it runs different ghc-mod installed somewhere on your system. This *is* ultimately an error produced by ghc-mod, so all parts before it seem to be working fine.

You could try enabling 'Debug' option in haskell-ghc-mod settings to see if it spits out anything interesting into console (or post a gist, so I could take a look)

**Comment by ThomasLocke** [comment] 2017-03-14 09:00
I've dumped a console log gist to the haskell-ghc-mod issue.

I only have one ghc-mod installed on the system.

**Comment by lierdakil** [comment] 2017-03-14 09:06
I'll close this in favor of https://github.com/atom-haskell/haskell-ghc-mod/issues/207. Let's keep this to one place.

**Closed by lierdakil** 2017-03-14 09:06 UTC
