### ISSUE TITLE
RegularPatterns extension is no longer supported, but the plugin recommends it.

### ISSUE THREAD

**Issue by mrakgr** [atom-haskell/ide-haskell#160] opened 2016-05-16 07:00 UTC
See this [SO question](http://stackoverflow.com/questions/37224366/how-to-resolve-an-unsupported-extension-regularpatterns-error) for a description of the problem. Sorry, if this is the wrong Github repo to report this.

**Comment by lierdakil** [comment] 2016-05-16 07:27
I'm not entirely sure what exactly suggests `RegularPatterns` to you. What panel is it displayed at? Error? Lint?

What tooling do you use? Which GHC version? Which ghc-mod version? Which hlint version?

**Comment by lierdakil** [comment] 2016-05-16 07:32
Also I will guess that you're developing on Windows. How did you install GHC and friends?

**Comment by mrakgr** [comment] 2016-05-16 07:44
Let me go through this one by one. Here is the offending code:
```haskell
module Main where
import Data.Char

data States =
  SentenceStart
  | SentenceMiddle
  | Quoting

splitStr :: String -> String -> States -> String
splitStr ('\"':xs) acc (SentenceStart | SentenceStart) = -- <- Right here!
   splitStr xs ('\"':acc) Quoting
splitStr ('\"':xs) acc Quoting =
  splitStr xs ('\"':acc) SentenceMiddle
splitStr (x:xs) acc Quoting =
  splitStr xs (x:acc) Quoting
splitStr (' ':xs) acc SentenceStart =
  splitStr xs acc SentenceStart
splitStr xs acc SentenceStart =
  splitStr xs acc SentenceMiddle
splitStr (x:'.':'.':'.':xs) acc SentenceMiddle =
  splitStr xs ('\n':'.':'.':'.':x:acc) SentenceStart
splitStr ('D':'r':'.':xs) acc SentenceMiddle =
  splitStr xs ('.':'r':'D':acc) SentenceMiddle
splitStr ('M':'r':'.':xs) acc SentenceMiddle =
  splitStr xs ('.':'r':'M':acc) SentenceMiddle
splitStr ('M':'i':'s':'s':'.':xs) acc SentenceMiddle =
  splitStr xs ('.':'s':'s':'i':'M':acc) SentenceMiddle
splitStr ('P':'r':'o':'f':'.':xs) acc SentenceMiddle =
  splitStr xs ('.':'f':'o':'r':'P':acc) SentenceMiddle
splitStr (x:'.':xs) acc SentenceMiddle
  | isUpper x = splitStr xs ('.':x:acc) SentenceMiddle
  | otherwise = splitStr xs ('\n':'.':x:acc) SentenceStart
splitStr (x:'?':xs) acc SentenceMiddle =
  splitStr xs ('\n':'?':x:acc) SentenceStart
splitStr (x:'!':xs) acc SentenceMiddle =
  splitStr xs ('\n':'!':x:acc) SentenceStart
splitStr (x:xs) acc SentenceMiddle =
  splitStr xs (x:acc) SentenceMiddle
splitStr [] acc _ = acc

main :: IO ()
main = do
  str <- getLine
  putStr $ reverse $ splitStr str [] SentenceStart --"This is a sentence. \"This is one.\", I said. This is another." [] SentenceStart
```
Editor - Atom 1.7.3.
Haskell related packages - 
autocomplete-haskell 0.6.5
haskel-ghc-mod 1.12.6
ide-haskell 1.6.3
ide-haskell-cabal 1.3.2
language-haskell 1.7.15

As you can see, I install Haskell via Haskell platform less than a week ago.
```
C:\!Haskell\From Paragraphs To Sentences>ghc -v
Glasgow Haskell Compiler, Version 7.10.3, stage 2 booted by GHC version 7.10.2
Using binary package database: C:\Program Files\Haskell Platform\7.10.3\lib\package.conf.d\package.cache
```
```
C:\!Haskell\From Paragraphs To Sentences>ghc-mod --version
ghc-mod version 5.5.0.0 compiled by GHC 7.10.3
```
```
C:\!Haskell\From Paragraphs To Sentences>hlint --version
HLint v1.9.26, (C) Neil Mitchell 2006-2016
```

I guess this is a problem with `hlint`. See this.
```
C:\!Haskell\From Paragraphs To Sentences>hlint parsey.hs
parsey.hs:10:56: Warning: Parse error: RegularPatterns language extension is not enabled. Please add {-# LANGUAGE RegularPatterns #-} pragma at the top of your module.
Found:
    splitStr :: String -> String -> States -> String
  > splitStr ('\"':xs) acc (SentenceStart | SentenceStart) =
       splitStr xs ('\"':acc) Quoting
    splitStr ('\"':xs) acc Quoting =

1 suggestion
```
Should I open an issue on the `hlint` page?

**Comment by lierdakil** [comment] 2016-05-16 07:54
This particular message seems to be generated from the depths of haskell-src-exts package, so I don't think it's hlint's fault. It might be a good idea to file an issue though, since this message is a bit (a fair bit) confusing.

However, when using ide-haskell, it doesn't seem to happen. Do you use [linter-hlint](https://atom.io/packages/linter-hlint) or something?

**Comment by mrakgr** [comment] 2016-05-16 07:58
No, just those packages mentioned above.

**Comment by lierdakil** [comment] 2016-05-16 08:12
Huh. Okay. I think I found a bug somewhere then. Anyway, try talking about this on https://github.com/ndmitchell/hlint/issues

**Comment by ndmitchell** [comment] 2016-05-16 09:12
I've raised this directly to haskell-src-exts as https://github.com/haskell-suite/haskell-src-exts/issues/305 - hlint can't supress this message on its own.

**Comment by ndmitchell** [comment] 2020-03-15 20:36
Confirmed doesn't suggest that extension with HEAD that doesn't use HSE for parsing, so fixed in the next release.

**Comment by lierdakil** [comment] 2020-03-16 11:24
Reportedly fixed in the upcoming hlint release.

**Closed by lierdakil** 2020-03-16 11:24 UTC
Labels: upstream
