### ISSUE TITLE
Auto-imports

### ISSUE THREAD

**Issue by joozek78** [atom-haskell/ide-haskell#60] opened 2015-05-27 22:00 UTC
It would be super-cool to have ide-haskell automatically resolve imports. Manually importing is very tedious (especially if you added a lot of symbols from external modules) and could be easily (I think) automated

**Comment by lierdakil** [comment] 2015-05-28 01:10
Apparently, you are new to Haskell. Automatic function name resolution across modules is simply impossible, since many modules have functions with similar names.

That's by design -- many modules are intended to be used with qualified imports.

So no, while it would be fun, it's simply not something I (or I assume anyone) can achieve to a satisfactory degree.

If I misudrestood your request, feel free to explain what you meant in more detail and reopen. Closing for now as wontfix.

**Comment by joozek78** [comment] 2015-05-28 07:54
I know what you mean, but it would be actually beneficial if I could select
my import from a few proposed (e.g. text builder lazy vs strict) than
manually find and type module name. Maybe I should present flow I have in
mind:
# user points to unresolved symbol and invokes "auto-import"
# ide-haskell checks list of modules that contain such symbol (maybe using
local hoogle?) and presents them to user
# user selects chosen module and it's automatically imported

If this is impossible (due to difficulty in finding potential imports) then
maybe just make importing easier with autocompletion.

**Comment by joozek78** [comment] 2015-05-28 07:58
I know what you mean, but it would be actually beneficial if I could select my import from a few proposed (e.g. text builder lazy vs strict) than manually find and type module name. Maybe I should present flow I have in mind:

1. user points to unresolved symbol and invokes "auto-import"
1. ide-haskell checks list of modules that contain such symbol (maybe using local hoogle?) and presents them to user
1. user selects chosen module and it's automatically imported


My current flow is:

1. user finds unresolved symbol
1. user goes to hoogle and searches for the symbol. Selects the right import
1. user goes back to editor, to the top of file and manually types the import
1. user now has to go back to where he was previously in file

If this is impossible (due to difficulty in finding potential imports) then maybe just make importing easier with autocompletion.

**Comment by lierdakil** [comment] 2015-05-28 15:02
Autocomplete-haskell already supports autocompletion for modules and module symbols (latter can be a little slow though, since requires to get module symbols on the fly). In a bit, I hope to fix language-haskell snippets, so that would also become an option.

I'm reluctant to use local hoogle, since my experience with it wasn't very nice (rebuilding local database was challenging at times, making it work with cabal sandboxes is a nightmare, etc), and gathering all exports from every module installed in the system... well, that's NOT going to be fast, and will likely be RAM-heavy. Technically, I think I could cache imports, but, well... to be frank, I'm not too keen on re-implementing hoogle in coffeescript.

There is some sense in this proposal though, so I think I'll reopen and let it sit for a while.

If anyone has interest in implementing this or wants this implemented, feel free to speak your mind.

**Comment by rvion** [comment] 2015-05-28 19:24
I have a real interest in this.
I might give it a try once, but can't now. 
If someone else want to give it a try, please, do so :)

Few notes
 - Stackage hosts hoogle db ready to use.
 - Hoogle is being rebuilt, and db generation will be much faster. New version handle generation of symbol DB really fast already and could be used here.

**Comment by lierdakil** [comment] 2015-05-28 19:32
Actually, now that I think about it, with sufficiently recent ghc-mod this might be somewhat easier to implement with `ghc-mod find` than fumble with hoogle (hoogle would be a tad bit faster though, but it's not very strict when searching, so that would present a challenge).

That said, I'm not sure I understand how to actually implement this in frontend in terms of user interface.

**Comment by rvion** [comment] 2015-05-28 20:08
Eclipse (from what I remember) add a small icon in the gutter.
When clicked, a pane appears with found modules exporting given term.

An easy, instantaneous, (but static and incomplete) way would be to loop through all modules here:
https://www.stackage.org/snapshot/lts-2.10/docs, and populate a textual key-value DB.

  - key would be the function symbol
  - value would be an array of modules it's defined in.

@lierdakil also, if you play with the new hoogle here: http://hoogle.haskell.org/?hoogle=test
you can see that search by term is damn fast :)

**Comment by lierdakil** [comment] 2015-05-28 22:29
I never doubted that hoogle is fast. It's not very precise though.

Autocompletion backend already has information on all system modules available, actually. It's just not a very fast process to get all exported symbols from them.

There is also `ghc-mod find` available starting from `ghc-mod-4.1.0`, which would be a reasonable option. It's not very fast though, but definitely faster than getting all symbols from all modules. I think I have a reasonable understanding of how to implement backend for this.

**Comment by lierdakil** [comment] 2015-05-29 21:08
I've added some stubs for `ghc-mod find` to `haskell-ghc-mod` and `ide-haskell`. For now, `ide-haskell:insert-import` command just prints modules for symbol under text cursor to dev console. Anyone willing to pick this up is welcome to.

**Comment by lierdakil** [comment] 2015-06-09 14:36
v0.5.11 implements a crude representation of this request. Main problem at the moment is parsing existing imports list and inserting into it, instead of just adding at the end.

You need at least one import statement in your file for "insert import" command to work.

**Comment by angerman** [comment] 2016-01-19 13:05
Seeing this as open, what's the current state of this?

**Comment by lierdakil** [comment] 2016-01-19 13:23
Inserting import works, for the most part. There is no support for
qualified imports, hidden symbols etc, however, and import statement is not
always inserted at the correct location. I have a plan on how to proceed
from here, but didn't get to it yet.
19 янв. 2016 г. 16:05 пользователь "Moritz Angermann" <
notifications@github.com> написал:

**Comment by angerman** [comment] 2016-01-19 13:36
Thanks for letting me know!

**Comment by Miguelme** [comment] 2017-07-03 00:08
Is this currently working ? How would be an example of usage let's say for the 'sort' function to auto-import Data.List ?

**Comment by lierdakil** [comment] 2017-07-03 03:07
`haskell-ghc-mod:insert-import` command:

![auto-import-cut](https://user-images.githubusercontent.com/7275622/27776702-96006af6-5fb5-11e7-976b-88483ef1961e.gif)

**Comment by XperianPro** [comment] 2017-08-21 19:18
What about 

> haskell-ghc-mod:insert-import-selective

where instead of importing whole module it would only import selected function from that module

ex. `import Module (selectedfunction)`

Also if it exists,it would be appended.

I think this feature could save quite some time and make code much more readable if used.
Thoughts?

**Comment by Miguelme** [comment] 2017-08-21 21:19
Thanks for the example @lierdakil . @XperianPro I honestly think that could be a great approach since we already have the current implementation.

**Comment by lierdakil** [comment] 2017-08-21 22:50
@XperianPro, 

> ex. import Module (selectedfunction)

is relatively simple, but

> Also if import exists,it would be appended to list.

is notoriously hard to get right. There's a lot of syntax to consider, and sometimes a module is imported twice (or more, but that's bad style). This is, however, doable in principle. I think it might be possible to use haskell-src-exts for both parsing and manipulation, but how that pans out is an open question.

**Comment by ron-wolf** [comment] 2017-11-02 01:58
`ghc` already suggests augmenting existing module imports with additional functions and data types/constructors. No matter how “undecidable“ this problem is, no matter how hard it is to solve perfectly, even a small effort would make package management _waaaay_ easier.

**Comment by lierdakil** [comment] 2017-11-03 10:25
I just don't have time to implement anything too sophisticated right now. Certainly not something that could parse arbitrary import statements. And "not sophisticated" is what we have right now. Pull requests are welcome.

**Closed** 2021-03-14 20:44 UTC
Labels: enhancement, help wanted, in progress
