### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dispose' of null

### ISSUE THREAD

**Issue by ncreep** [atom-haskell/ide-haskell#57] opened 2015-05-25 22:43 UTC
Using `ide-haskel` `0.5.1` I get `Uncaught TypeError: Cannot read property 'dispose' of null` error when closing a tab.

The offending line is `editor-control.coffee:154`:
```
@tooltipMarkers.dispose()
```

Changing it to:
```
@tooltipMarkers?.dispose()
```
fixes the issue in my use case. But maybe there's a more serious issue with the life-cycle of the `@tooltipMarkers` property.

**Comment by lierdakil** [comment] 2015-05-25 22:54
Thank you for report, but it's duplicate of #56. Fixed in 0.5.2

**Closed by lierdakil** 2015-05-25 22:54 UTC
Labels: duplicate

**Comment by ncreep** [comment] 2015-05-25 22:56
Oops, sorry. When I searched for  the issue it wasn't created yet...

**Comment by lierdakil** [comment] 2015-05-25 22:59
I figured that might be it, so no problem. Thank you again for taking time to report this, I greatly appreciate it, even if it's duplicate :+1:
